#!/bin/python

# plot output data from test given datasets

import matplotlib.pyplot as plt
import argparse
import sys
import numpy as np

descrip = "script for plotting output data file from linear advection code for comparing initial and final state."
data_help = "input data file containing the physical coordinate and state, the first column is the physical coordinate x, and the second column is the state info."
xlim_help = "Limit on the physical x-domain, enter in lower then upper limit"
ylim_help = "Limit on the physical y-domain, enter in lower then upper limit"

parser = argparse.ArgumentParser(description=descrip)
parser.add_argument('data', nargs='+', help= data_help)
parser.add_argument('-x',"--xlim", nargs=2, default=['0','1'],help= xlim_help)
parser.add_argument('-y',"--ylim", nargs=2, default=['0','1'],help= ylim_help) 

# [1:] to exclude namespace of running the program, e.g. ./plot
args = parser.parse_args(sys.argv[1:])

# Get xlim and ylim
x = list(map(float, args.xlim))
y = list(map(float, args.ylim))

extent = x+y

for dataset in args.data:
    fig = plt.figure(figsize=(7,7))
    ax = fig.add_subplot(111)
    data = np.loadtxt(dataset)
    im = ax.imshow(data, cmap = plt.cm.viridis, vmin=np.amin(data), vmax=np.amax(data), extent=extent, interpolation = None)
    fig.colorbar(im,ax=ax)
    plt.show(block=True)
    #fig.savefig('figure.png')
# plt.show()
