#!/bin/python

# plot output data from test given datasets

import matplotlib.pyplot as plt
import argparse
import sys
import numpy as np

descrip = "script for plotting output data file from linear advection code for comparing initial and final state."
data_help = "input data file containing the physical coordinate and state, the first column is the physical coordinate x, and the second column is the state info."

parser = argparse.ArgumentParser(description=descrip)
parser.add_argument('data', nargs='+', help= data_help)

# [1:] to exclude namespace of running the program, e.g. ./plot
args = parser.parse_args(sys.argv[1:])

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111)

for dataset in args.data:
    data = np.loadtxt(dataset)
    ax.plot(data[:,0], data[:,1], label = dataset)
    
ax.set_xlabel('X')
ax.set_ylabel('State')
ax.legend()
#fig.savefig('figure.png')
plt.show()
